version: "3"
networks:
  api_server_default:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 3000:3000
